package claimtypes

const (
	// Basic JWT
	Issuer    string = "iss"
	IssuedAt  string = "iat"
	ExpiresAt string = "exp"
	NotBefore string = "nbf"
	Audience  string = "aud"
	Subject   string = "sub"

	Name                  string = "name"
	GivenName             string = "given_name"
	FamilyName            string = "family_name"
	MiddleName            string = "middle_name"
	NickName              string = "nickname"
	PreferredUserName     string = "preferred_username"
	Profile               string = "profile"
	Picture               string = "picture"
	Email                 string = "email"
	EmailVerified         string = "email_verified"
	Gender                string = "gender"
	BirthDate             string = "birthdate"
	ZoneInfo              string = "zoneinfo"
	Locale                string = "locale"
	PhoneNumber           string = "phone_number"
	PhoneNumberVerified   string = "phone_number_verified"
	Address               string = "address"
	UpdatedAt             string = "updated_at"
	AuthorizedParty       string = "azp"
	Nonce                 string = "nonce"
	AuthenticationTime    string = "auth_time"
	AccessTokenHash       string = "at_hash"
	AuthorizationCodeHash string = "c_hash"
	IdentityProvider      string = "idp"
	JwtId                 string = "jti"
	Role                  string = "role"
	Scope                 string = "scope"
	ClientId              string = "client_id"
)
