version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/cmd/identity-server"
      - "/router/*"
      - "/store/*"
    schedule:
      interval: "weekly"
    labels:
      - "golang"
      - "dependencies"
