name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        cache: true

    - name: Install dependencies
      run: |
        go install github.com/golang/mock/mockgen@v1.6.0
        go install github.com/go-swagger/go-swagger/cmd/swagger@v0.30.4

    - name: Generate
      run: go generate -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...